version: '3.8'

services:
  web:
    build: .
    command: /app/entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=secret-key
      - POSTGRES_DB=auth_system
      - POSTGRES_USER=auth_user
      - POSTGRES_PASSWORD=auth_password
      - DATABASE_HOST=db
      - POSTGRES_PORT=5432
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
    depends_on:
      - db
    networks:
      - auth_network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=auth_system
      - POSTGRES_USER=auth_user
      - POSTGRES_PASSWORD=auth_password
    networks:
      - auth_network

volumes:
  postgres_data:

networks:
  auth_network:
    driver: bridge